name = "CMCModels"
uuid = "8a844b39-05e3-4819-8383-f5fae2d66f33"
authors = ["JuliaHub, Inc. and other contributors"]
version = "0.1.0"

[deps]
Cadnip = "28ce5535-9df1-4533-abc1-da0fb7327efb"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
NyanVerilogAParser = "28caa042-5edb-4d1f-abcd-02ce41b2dd3d"

[sources]
Cadnip = {path = "../.."}
NyanVerilogAParser = {path = "../../NyanVerilogAParser.jl"}

[compat]
Cadnip = "0.12"
ForwardDiff = "0.10, 1"
NyanVerilogAParser = "0.3"
julia = "1.11"
