name = "NyanSpectreNetlistParser"
uuid = "f050a39a-f089-4c65-a86a-958b8b907b9b"
authors = ["JuliaHub, Inc. and other contributors"]
version = "0.6.1"

[workspace]
projects = ["docs", "test"]

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
NyanLexers = "d66291fa-f43e-4b10-8b90-d63ec5d3f0a1"
SnoopPrecompile = "66db9d55-30c0-4569-8b51-7e840670fc0c"

[sources]
NyanLexers = {path = "../NyanLexers.jl"}

[compat]
AbstractTrees = "≥ 0.4.1"
NyanLexers = "≥ 0.3"
SnoopPrecompile = "≥ 1.0"
julia = "1.9"
