#==============================================================================#
# MNA Phase 1: Basic Device Stamps
#
# This module provides stamp! methods for basic circuit elements.
# Each device type has a corresponding stamp! method that adds its
# contribution to the MNA matrices (G, C) and RHS vector (b).
#
# Devices implemented:
# - Resistor: stamps conductance G = 1/R
# - Capacitor: stamps capacitance C
# - Inductor: stamps inductance L (with current variable)
# - VoltageSource: stamps voltage constraint (with current variable)
# - CurrentSource: stamps source current into RHS
# - VCVS, VCCS: voltage-controlled sources
#==============================================================================#

using StaticArrays: SVector

#==============================================================================#
# PWL Interpolation (from Cadnip.spectre_env.jl)
# Included here because MNA is loaded before spectre_env.jl
#==============================================================================#

"""
    find_t_in_ts(ts, t) -> Int

Find the index in sorted array `ts` where `t` would be inserted.
Uses searchsortedfirst for O(log n) lookup on SVector.
"""
@inline function find_t_in_ts(ts, t)
    idx = Base.searchsortedfirst(ts, t)
    if idx <= length(ts) && ts[idx] == t
        return idx + 1
    end
    return idx
end

"""
    pwl_at_time(ts, ys, t) -> value

Evaluate piecewise-linear function at time t.
Works with SVector (uses searchsortedfirst for O(log n) lookup).

Handles edge cases: before first point, after last point, flat segments,
and infinitely steep segments (same time, different values).
"""
@inline function pwl_at_time(ts, ys, t)
    i = find_t_in_ts(ts, t)
    type_stable_time = 0.0 * t  # Preserves type (e.g., ForwardDiff.Dual)
    if i <= 1
        # Signal is before the first timepoint, hold the first value.
        return ys[1] + type_stable_time
    end
    if i > length(ts)
        # Signal is beyond the final timepoint, hold the final value.
        return ys[end] + type_stable_time
    end
    begin
        if ys[i-1] == ys[i]
            # signal is constant/flat (singularity in y)
            return ys[i] + type_stable_time
        end
        if ts[i] == ts[i-1]
            # signal is infinitely steep (singularity in t)
            return (ys[i-1] + ys[i])/2 + type_stable_time
        end
        # The general case: linear interpolation
        slope = (ys[i] - ys[i-1])/(ts[i] - ts[i-1])
        return ys[i-1] + (t - ts[i-1])*slope
    end
end

"""
    pulse_at_time(v1, v2, td, tr, tf, pw, per, t) -> value

Evaluate a SPICE PULSE source at time `t`.

- Before the delay `td`, holds the initial value `v1`.
- From `td` onward the waveform repeats with period `per`: a linear rise from
  `v1` to `v2` over `tr`, a flat top at `v2` for `pw`, a linear fall back to
  `v1` over `tf`, then a flat bottom at `v1` for the rest of the period.

A non-positive `per` produces a single (non-repeating) pulse.
"""
@inline function pulse_at_time(v1, v2, td, tr, tf, pw, per, t)
    type_stable_time = 0.0 * t  # Preserves type (e.g. ForwardDiff.Dual)
    if t < td
        return v1 + type_stable_time
    end
    # Phase within the current period; a single pulse when per <= 0.
    phase = per > 0 ? mod(t - td, per) : (t - td)
    if phase < tr
        # Rising edge (instantaneous if tr == 0)
        return tr > 0 ? v1 + (v2 - v1) * (phase / tr) : v2 + type_stable_time
    elseif phase < tr + pw
        return v2 + type_stable_time
    elseif phase < tr + pw + tf
        # Falling edge (instantaneous if tf == 0)
        return tf > 0 ? v2 + (v1 - v2) * ((phase - tr - pw) / tf) : v1 + type_stable_time
    else
        return v1 + type_stable_time
    end
end

export stamp!
export Resistor, Capacitor, Inductor
export VoltageSource, CurrentSource
export VCVS, VCCS, CCVS, CCCS
export pwl_at_time, pulse_at_time

#==============================================================================#
# Wave Callable Structs
#
# Callable replacements for the anonymous `tran = _t -> ...` closures
# generated by spc/codegen.jl. Being concrete structs (rather than closures)
# makes their breakpoint times enumerable from the constructed object at
# build time via `breakpoints(wave)` (see breakpoints.jl) - params may be
# runtime expressions, so parse-time extraction from the netlist would be
# wrong.
#==============================================================================#

"""
    PWLWave(ts, ys)

Callable piecewise-linear waveform: `PWLWave(ts, ys)(t) == pwl_at_time(ts, ys, t)`.

`ts`/`ys` are either both `SVector{N,Float64}` (zero-allocation path, compile-time
constant vertex count) or both `Vector{Float64}` (dynamic fallback).
"""
struct PWLWave{TS,YS} <: Wave
    ts::TS
    ys::YS
end

@inline (w::PWLWave)(t::Real) = pwl_at_time(w.ts, w.ys, t)

"""
Breakpoints at every PWL vertex time - the integrator should land exactly on
each vertex to resolve the kink in slope there.

`Vector{Float64}(ts)` rather than `collect`/comprehension: StaticArrays makes
those return a `SizedVector` for `SVector` input, while the Array constructor
always yields a plain (freshly copied) `Vector{Float64}`.
"""
breakpoints(w::PWLWave) = BreakpointSpec(Vector{Float64}(w.ts))

export PWLWave

"""
    SinWave(vo, va, freq, td, theta, phase)

Callable SPICE SIN source: constant `vo + va*sind(phase)` before `td`, then
`vo + va*exp(-theta*(t-td))*sind(360*freq*(t-td) + phase)`.
"""
struct SinWave <: Wave
    vo::Float64
    va::Float64
    freq::Float64
    td::Float64
    theta::Float64
    phase::Float64
end

function SinWave(vo::Real, va::Real, freq::Real, td::Real=0.0, theta::Real=0.0, phase::Real=0.0)
    SinWave(Float64(vo), Float64(va), Float64(freq), Float64(td), Float64(theta), Float64(phase))
end

@inline function (w::SinWave)(t::Real)
    if t < w.td
        w.vo + w.va * sind(w.phase)
    else
        w.vo + w.va * exp(-w.theta * (t - w.td)) * sind(360 * w.freq * (t - w.td) + w.phase)
    end
end

"""
The onset at `td` is a slope discontinuity (value is continuous, derivative
jumps from 0 to the sinusoid's slope) - a breakpoint hint when `td > 0`.
"""
breakpoints(w::SinWave) = w.td > 0 ? BreakpointSpec(Float64[w.td]) : nothing

export SinWave

"""
    PulseWave(v1, v2, td, tr, tf, pw, per)

Callable SPICE PULSE source: see `pulse_at_time` for the waveform definition.
"""
struct PulseWave <: Wave
    v1::Float64
    v2::Float64
    td::Float64
    tr::Float64
    tf::Float64
    pw::Float64
    per::Float64
end

function PulseWave(v1::Real, v2::Real, td::Real, tr::Real, tf::Real, pw::Real, per::Real)
    PulseWave(Float64(v1), Float64(v2), Float64(td), Float64(tr), Float64(tf), Float64(pw), Float64(per))
end

@inline (w::PulseWave)(t::Real) = pulse_at_time(w.v1, w.v2, w.td, w.tr, w.tf, w.pw, w.per, t)

"""
Breakpoints at each edge (rise start, flat-top start, fall start, flat-bottom
start) within the first period, repeated every `per` seconds when `per > 0`
(a non-positive `per` is a single non-repeating pulse, matching
`pulse_at_time`).
"""
function breakpoints(w::PulseWave)
    edges = Float64[w.td, w.td + w.tr, w.td + w.tr + w.pw, w.td + w.tr + w.pw + w.tf]
    return w.per > 0 ? BreakpointSpec(edges, w.per, -1) : BreakpointSpec(edges)
end

export PulseWave

#==============================================================================#
# Device Type Hierarchy
#
# Abstract types for device categorization:
# - AbstractMNADevice: base type for all devices
# - AbstractVoltageSource: devices that create a current variable (for KVL constraint)
# - AbstractCurrentSource: devices that inject current but don't create variables
#
# Key distinction: Voltage sources create current variables that can be referenced
# by controlled sources (CCVS, CCCS). Current sources only modify the RHS vector.
#==============================================================================#

"""Base type for all MNA circuit devices."""
abstract type AbstractMNADevice end

"""
Devices that impose a voltage constraint and create a current variable.

All voltage sources (independent, controlled, behavioral) create a current variable
in the MNA system. This current can be referenced by CCVS/CCCS controlled sources.
"""
abstract type AbstractVoltageSource <: AbstractMNADevice end

"""
Devices that inject/absorb current without creating additional variables.

Current sources only modify the RHS vector `b`, they don't add variables to the system.
"""
abstract type AbstractCurrentSource <: AbstractMNADevice end

"""Passive devices (resistors, capacitors, inductors)."""
abstract type AbstractPassiveDevice <: AbstractMNADevice end

export AbstractMNADevice, AbstractVoltageSource, AbstractCurrentSource, AbstractPassiveDevice

#==============================================================================#
# Device Types
#==============================================================================#

"""
    Resistor(r::Float64; name::Symbol=:R)

A linear resistor with resistance `r` ohms.

MNA stamps G matrix only (resistive, no dynamics).
"""
struct Resistor <: AbstractPassiveDevice
    r::Float64
    name::Symbol
end
Resistor(r::Real; name::Symbol=:R) = Resistor(Float64(r), name)

"""
    Capacitor(c::Float64; name::Symbol=:C)

A linear capacitor with capacitance `c` farads.

MNA stamps C matrix only (reactive dynamics).
"""
struct Capacitor <: AbstractPassiveDevice
    c::Float64
    name::Symbol
end
Capacitor(c::Real; name::Symbol=:C) = Capacitor(Float64(c), name)

"""
    Inductor(l::Float64; name::Symbol=:L)

A linear inductor with inductance `l` henries.

MNA requires a current variable (I_L is a state variable).
Stamps G matrix (KCL and voltage constraint) and C matrix (V = L*dI/dt).
"""
struct Inductor <: AbstractPassiveDevice
    l::Float64
    name::Symbol
end
Inductor(l::Real; name::Symbol=:L) = Inductor(Float64(l), name)

#==============================================================================#
# Unified VoltageSource
#==============================================================================#

"""
    VoltageSource{F}

Unified voltage source with dc/ac/tran support.

# Fields
- `dc::Float64`: DC value for DC operating point analysis
- `ac::ComplexF64`: AC phasor for small-signal AC analysis
- `tran::F`: Transient function `t -> value`, or `nothing` to use dc
- `name::Symbol`: Source name

# Analysis Modes
- `:dcop` -> returns `dc`
- `:ac` -> returns `dc` (AC phasor handled separately by AC solve)
- `:tran` -> calls `tran(t)` if not nothing, else returns `dc`

# Examples
```julia
# Simple DC source
v1 = VoltageSource(5.0; name=:V1)

# DC + AC source (for AC analysis)
v2 = VoltageSource(0.0; ac=1.0, name=:Vin)

# Transient source with function
v3 = VoltageSource(0.0; tran=t -> 5.0 * sin(2π * 1000 * t), name=:Vsin)
```
"""
struct VoltageSource{F} <: AbstractVoltageSource
    dc::Float64
    ac::ComplexF64
    tran::F
    name::Symbol
end

# Simple DC source: VoltageSource(5.0)
function VoltageSource(v::Real; ac::Number=0.0+0.0im, tran=nothing, name::Symbol=:V)
    VoltageSource{typeof(tran)}(Float64(v), ComplexF64(ac), tran, name)
end

export VoltageSource

"""
    get_source_value(src::VoltageSource, t::Real, mode::Symbol) -> Float64

Get the source value at time `t` for the given simulation mode.

- `:dcop` -> returns DC value
- `:ac` -> returns DC value (AC phasor handled by AC solve)
- `:tran` -> calls tran(t) if not nothing, else returns dc
"""
@inline function get_source_value(src::VoltageSource{Nothing}, t::Real, mode::Symbol)
    return src.dc
end

@inline function get_source_value(src::VoltageSource{F}, t::Real, mode::Symbol) where {F}
    mode === :dcop && return src.dc
    mode === :ac && return src.dc
    return src.tran(t)
end

export get_source_value

#==============================================================================#
# Unified CurrentSource
#==============================================================================#

"""
    CurrentSource{F}

Unified current source with dc/ac/tran support.

# Fields
- `dc::Float64`: DC value for DC operating point analysis
- `ac::ComplexF64`: AC phasor for small-signal AC analysis
- `tran::F`: Transient function `t -> value`, or `nothing` to use dc
- `name::Symbol`: Source name

Stamps b vector only (source current into KCL equations).
Positive current flows from n to p (into the positive terminal).
"""
struct CurrentSource{F} <: AbstractCurrentSource
    dc::Float64
    ac::ComplexF64
    tran::F
    name::Symbol
end

# Simple DC source: CurrentSource(1e-3)
function CurrentSource(i::Real; ac::Number=0.0+0.0im, tran=nothing, name::Symbol=:I)
    CurrentSource{typeof(tran)}(Float64(i), ComplexF64(ac), tran, name)
end

export CurrentSource

@inline function get_source_value(src::CurrentSource{Nothing}, t::Real, mode::Symbol)
    return src.dc
end

@inline function get_source_value(src::CurrentSource{F}, t::Real, mode::Symbol) where {F}
    mode === :dcop && return src.dc
    mode === :ac && return src.dc
    return src.tran(t)
end

"""
    VCVS(gain::Float64; name::Symbol=:E)

Voltage-Controlled Voltage Source.
V(out+, out-) = gain * V(in+, in-)

Requires a current variable for the output branch.
"""
struct VCVS <: AbstractVoltageSource
    gain::Float64
    name::Symbol
end
VCVS(gain::Real; name::Symbol=:E) = VCVS(Float64(gain), name)

"""
    VCCS(gm::Float64; name::Symbol=:G)

Voltage-Controlled Current Source (transconductance amplifier).
I(out+, out-) = gm * V(in+, in-)

Does not require a current variable.
"""
struct VCCS <: AbstractCurrentSource
    gm::Float64
    name::Symbol
end
VCCS(gm::Real; name::Symbol=:G) = VCCS(Float64(gm), name)

"""
    CCVS(rm::Float64; name::Symbol=:H)

Current-Controlled Voltage Source (transresistance amplifier).
V(out+, out-) = rm * I(in+, in-)

Requires current variables for both input and output branches.
"""
struct CCVS <: AbstractVoltageSource
    rm::Float64
    name::Symbol
end
CCVS(rm::Real; name::Symbol=:H) = CCVS(Float64(rm), name)

"""
    CCCS(gain::Float64; name::Symbol=:F)

Current-Controlled Current Source.
I(out+, out-) = gain * I(in+, in-)

Requires a current variable for the input (sensing) branch.
"""
struct CCCS <: AbstractCurrentSource
    gain::Float64
    name::Symbol
end
CCCS(gain::Real; name::Symbol=:F) = CCCS(Float64(gain), name)

#==============================================================================#
# Stamp Methods
#==============================================================================#

"""
    stamp!(device, ctx::AnyMNAContext, ports...)

Stamp a device into the MNA context.

The number and meaning of ports depends on the device type:
- 2-terminal devices (R, C, L, V, I): stamp!(dev, ctx, p, n)
- 4-terminal sources (VCVS, VCCS): stamp!(dev, ctx, out_p, out_n, in_p, in_n)
"""
function stamp! end

#------------------------------------------------------------------------------#
# Resistor: G matrix only
#------------------------------------------------------------------------------#

"""
    stamp!(R::Resistor, ctx::AnyMNAContext, p::Int, n::Int)

Stamp a resistor between nodes p and n.

The resistor contributes I = (Vp - Vn)/R to KCL at each node.
Using "current leaving node is positive" convention:
- KCL at p: +G*Vp - G*Vn (current leaves p)
- KCL at n: -G*Vp + G*Vn (current enters n)

Matrix pattern (for G = 1/R):
```
     Vp  Vn
Vp [ +G  -G ]
Vn [ -G  +G ]
```
"""
function stamp!(R::Resistor, ctx::AnyMNAContext, p::Int, n::Int)
    G = 1.0 / R.r
    stamp_conductance!(ctx, p, n, G)
    return nothing
end

#------------------------------------------------------------------------------#
# Capacitor: C matrix only
#------------------------------------------------------------------------------#

"""
    stamp!(C::Capacitor, ctx::AnyMNAContext, p::Int, n::Int)

Stamp a capacitor between nodes p and n.

The capacitor contributes I = C * d(Vp - Vn)/dt to KCL.
This stamps into the C matrix with the same pattern as a resistor.

Matrix pattern:
```
     Vp  Vn
Vp [ +C  -C ]
Vn [ -C  +C ]
```
"""
function stamp!(C::Capacitor, ctx::AnyMNAContext, p::Int, n::Int)
    stamp_capacitance!(ctx, p, n, C.c)
    return nothing
end

#------------------------------------------------------------------------------#
# Inductor: G and C matrices, needs current variable
#------------------------------------------------------------------------------#

"""
    stamp!(L::Inductor, ctx::AnyMNAContext, p::Int, n::Int) -> Int

Stamp an inductor between nodes p and n.
Returns the index of the inductor current variable.

The inductor uses a current variable I_L because current is a state variable.
Equations:
1. KCL at p: current I_L leaves p
2. KCL at n: current I_L enters n
3. Voltage equation: V_p - V_n = L * dI_L/dt

Matrix pattern:
```
        Vp  Vn  I_L
    Vp [ .   .  +1  ]     KCL: I_L leaves p
    Vn [ .   .  -1  ]     KCL: I_L enters n
G = I_L[+1  -1   .  ]     Voltage: Vp - Vn

        Vp  Vn  I_L
    Vp [ .   .   .  ]
    Vn [ .   .   .  ]
C = I_L[ .   .  -L  ]     Voltage: ... = L * dI/dt
```

Note: The -L in C comes from rewriting V = L*dI/dt as:
      G*x + C*dx/dt = b
      Vp - Vn - L*dI/dt = 0
"""
function stamp!(L::Inductor, ctx::AnyMNAContext, p::Int, n::Int)
    # Allocate current variable using component-based API (zero allocation for DirectStampContext)
    I_idx = alloc_current!(ctx, :I_, L.name)

    # KCL: current I_L flows from p to n
    stamp_G!(ctx, p, I_idx,  1.0)
    stamp_G!(ctx, n, I_idx, -1.0)

    # Voltage equation: Vp - Vn - L*dI/dt = 0
    # G part: Vp - Vn
    stamp_G!(ctx, I_idx, p,  1.0)
    stamp_G!(ctx, I_idx, n, -1.0)

    # C part: -L * dI/dt
    stamp_C!(ctx, I_idx, I_idx, -L.l)

    return I_idx
end

#------------------------------------------------------------------------------#
# Voltage Source: G matrix and b vector, needs current variable
#------------------------------------------------------------------------------#

"""
    stamp!(V::VoltageSource, ctx::AnyMNAContext, p::Int, n::Int) -> Int

Stamp a voltage source between nodes p and n (V_p - V_n = V.dc).
Returns the index of the source current variable.

This is the simple DC stamp - for time-dependent analysis use the
version with time and mode arguments.

The voltage source needs a current variable because current is unknown.
Equations:
1. KCL at p: current I_V leaves p (enters source at + terminal)
2. KCL at n: current I_V enters n
3. Voltage equation: V_p - V_n = V_dc

Matrix pattern:
```
        Vp  Vn  I_V
    Vp [ .   .  +1  ]     KCL: I_V leaves p
    Vn [ .   .  -1  ]     KCL: I_V enters n
G = I_V[+1  -1   .  ]     Voltage constraint: Vp - Vn

    I_V
b = V_dc                  Source voltage value (DC)
b_ac = V_ac               Source voltage value (AC small-signal)
```
"""
function stamp!(V::VoltageSource, ctx::AnyMNAContext, p::Int, n::Int)
    # Allocate current variable using component-based API (zero allocation for DirectStampContext)
    I_idx = alloc_current!(ctx, :I_, V.name)

    # KCL: current I_V flows from p through source to n
    stamp_G!(ctx, p, I_idx,  1.0)
    stamp_G!(ctx, n, I_idx, -1.0)

    # Voltage equation: Vp - Vn = V_dc
    stamp_G!(ctx, I_idx, p,  1.0)
    stamp_G!(ctx, I_idx, n, -1.0)
    stamp_b!(ctx, I_idx, V.dc)

    return I_idx
end

"""
    stamp!(V::VoltageSource, ctx::AnyMNAContext, p::Int, n::Int, t::Real, mode::Symbol) -> Int

Stamp a voltage source with time and mode awareness.

For transient analysis, evaluates the source at time t.
For DC/AC analysis, uses the DC value.
"""
@inline function stamp!(V::VoltageSource, ctx::AnyMNAContext, p::Int, n::Int,
                        t::Real, mode::Symbol)
    # Component-based API for zero allocation in DirectStampContext
    I_idx = alloc_current!(ctx, :I_, V.name)
    register_breakpoints!(ctx, V.tran)

    stamp_G!(ctx, p, I_idx,  1.0)
    stamp_G!(ctx, n, I_idx, -1.0)
    stamp_G!(ctx, I_idx, p,  1.0)
    stamp_G!(ctx, I_idx, n, -1.0)

    v = get_source_value(V, t, mode)
    stamp_b!(ctx, I_idx, v)

    # AC excitation (for small-signal analysis)
    if V.ac != 0
        stamp_b_ac!(ctx, I_idx, V.ac)
    end

    return I_idx
end

#------------------------------------------------------------------------------#
# Current Source: b vector only
#------------------------------------------------------------------------------#

"""
    stamp!(I::CurrentSource, ctx::AnyMNAContext, p::Int, n::Int)

Stamp a current source between nodes p and n.
Positive current flows from n to p (into the positive terminal p).

This is the simple DC stamp - for time-dependent analysis use the
version with time and mode arguments.

KCL contributions:
- At p: current I.dc enters (positive term)
- At n: current I.dc leaves (negative term)

This follows the passive sign convention where current enters
the positive terminal.

RHS pattern:
```
    p
b = +I      (DC current enters p)
    n
    -I      (DC current leaves n)

    p
b_ac = +I_ac   (AC current enters p)
    n
       -I_ac   (AC current leaves n)
```
"""
function stamp!(I::CurrentSource, ctx::AnyMNAContext, p::Int, n::Int)
    # Current flows from n to p (into positive terminal)
    # KCL at p: current I enters (add to RHS)
    # KCL at n: current I leaves (subtract from RHS)
    stamp_b!(ctx, p,  I.dc)
    stamp_b!(ctx, n, -I.dc)
    return nothing
end

"""
    stamp!(I::CurrentSource, ctx::AnyMNAContext, p::Int, n::Int, t::Real, mode::Symbol)

Stamp a current source with time and mode awareness.

For transient analysis, evaluates the source at time t.
For DC/AC analysis, uses the DC value.
"""
@inline function stamp!(I::CurrentSource, ctx::AnyMNAContext, p::Int, n::Int,
                        t::Real, mode::Symbol)
    register_breakpoints!(ctx, I.tran)
    i = get_source_value(I, t, mode)
    stamp_b!(ctx, p,  i)
    stamp_b!(ctx, n, -i)

    # AC excitation (for small-signal analysis)
    if I.ac != 0
        stamp_b_ac!(ctx, p,  I.ac)
        stamp_b_ac!(ctx, n, -I.ac)
    end

    return nothing
end

#------------------------------------------------------------------------------#
# VCVS: Voltage-Controlled Voltage Source
#------------------------------------------------------------------------------#

"""
    stamp!(E::VCVS, ctx::AnyMNAContext, out_p::Int, out_n::Int, in_p::Int, in_n::Int) -> Int

Stamp a voltage-controlled voltage source.
V(out_p, out_n) = E.gain * V(in_p, in_n)

Returns the index of the output current variable.

Matrix pattern:
```
            out_p out_n in_p in_n I_E
out_p      [  .     .    .    .   +1 ]  KCL at out_p
out_n      [  .     .    .    .   -1 ]  KCL at out_n
G = I_E    [ +1    -1   -A   +A    . ]  Voltage: Vout - A*Vin = 0
```
where A = E.gain
"""
function stamp!(E::VCVS, ctx::AnyMNAContext, out_p::Int, out_n::Int, in_p::Int, in_n::Int)
    # Allocate current variable for output branch (zero allocation for DirectStampContext)
    I_idx = alloc_current!(ctx, :I_, E.name)

    # KCL at output nodes
    stamp_G!(ctx, out_p, I_idx,  1.0)
    stamp_G!(ctx, out_n, I_idx, -1.0)

    # Voltage equation: V(out_p) - V(out_n) - gain * (V(in_p) - V(in_n)) = 0
    stamp_G!(ctx, I_idx, out_p,  1.0)
    stamp_G!(ctx, I_idx, out_n, -1.0)
    stamp_G!(ctx, I_idx, in_p,  -E.gain)
    stamp_G!(ctx, I_idx, in_n,   E.gain)

    return I_idx
end

#------------------------------------------------------------------------------#
# VCCS: Voltage-Controlled Current Source
#------------------------------------------------------------------------------#

"""
    stamp!(G_dev::VCCS, ctx::AnyMNAContext, out_p::Int, out_n::Int, in_p::Int, in_n::Int)

Stamp a voltage-controlled current source (transconductance).
I(out_p, out_n) = G_dev.gm * V(in_p, in_n)

Current flows from out_n to out_p (into out_p).
No current variable needed.

Matrix pattern (MNA convention: current leaving is positive):
```
            out_p out_n in_p in_n
out_p      [  .     .   -gm  +gm ]  Current leaving out_p = -gm*Vin
G = out_n  [  .     .   +gm  -gm ]  Current leaving out_n = +gm*Vin
```
"""
function stamp!(G_dev::VCCS, ctx::AnyMNAContext, out_p::Int, out_n::Int, in_p::Int, in_n::Int)
    gm = G_dev.gm
    # I = gm * V(in_p, in_n) flows INTO out_p (from out_n)
    # MNA uses "current leaving is positive", so:
    # - Current leaving out_p = -gm * V(in_p, in_n)
    # - Current leaving out_n = +gm * V(in_p, in_n)
    stamp_G!(ctx, out_p, in_p, -gm)
    stamp_G!(ctx, out_p, in_n,  gm)
    stamp_G!(ctx, out_n, in_p,  gm)
    stamp_G!(ctx, out_n, in_n, -gm)
    return nothing
end

#------------------------------------------------------------------------------#
# CCVS: Current-Controlled Voltage Source
#------------------------------------------------------------------------------#

"""
    stamp!(H::CCVS, ctx::AnyMNAContext, out_p::Int, out_n::Int, in_p::Int, in_n::Int) -> Tuple{Int,Int}

Stamp a current-controlled voltage source (transresistance).
V(out_p, out_n) = H.rm * I(in_p, in_n)

Returns (I_out_idx, I_in_idx) - indices of output and input current variables.

The input branch is a zero-volt voltage source (ammeter) to sense current.
"""
function stamp!(H::CCVS, ctx::AnyMNAContext, out_p::Int, out_n::Int, in_p::Int, in_n::Int)
    # Input current variable (sensing branch: V = 0) - zero allocation for DirectStampContext
    I_in_idx = alloc_current!(ctx, :I_, H.name, :_in)

    # Output current variable - zero allocation for DirectStampContext
    I_out_idx = alloc_current!(ctx, :I_, H.name, :_out)

    # Input sensing branch (zero-volt source)
    stamp_G!(ctx, in_p, I_in_idx,  1.0)
    stamp_G!(ctx, in_n, I_in_idx, -1.0)
    stamp_G!(ctx, I_in_idx, in_p,  1.0)
    stamp_G!(ctx, I_in_idx, in_n, -1.0)
    # b[I_in_idx] = 0 (implicit)

    # Output branch
    stamp_G!(ctx, out_p, I_out_idx,  1.0)
    stamp_G!(ctx, out_n, I_out_idx, -1.0)

    # Voltage equation: V(out) = rm * I(in)
    # V(out_p) - V(out_n) - rm * I_in = 0
    stamp_G!(ctx, I_out_idx, out_p,     1.0)
    stamp_G!(ctx, I_out_idx, out_n,    -1.0)
    stamp_G!(ctx, I_out_idx, I_in_idx, -H.rm)

    return (I_out_idx, I_in_idx)
end

#------------------------------------------------------------------------------#
# CCCS: Current-Controlled Current Source
#------------------------------------------------------------------------------#

"""
    stamp!(F::CCCS, ctx::AnyMNAContext, out_p::Int, out_n::Int, in_p::Int, in_n::Int) -> Int

Stamp a current-controlled current source.
I(out_p, out_n) = F.gain * I(in_p, in_n)

Returns I_in_idx - the index of the input current variable.

The input branch is a zero-volt voltage source (ammeter) to sense current.
"""
function stamp!(F::CCCS, ctx::AnyMNAContext, out_p::Int, out_n::Int, in_p::Int, in_n::Int)
    # Input current variable (sensing branch) - zero allocation for DirectStampContext
    I_in_idx = alloc_current!(ctx, :I_, F.name, :_in)

    # Input sensing branch (zero-volt source)
    stamp_G!(ctx, in_p, I_in_idx,  1.0)
    stamp_G!(ctx, in_n, I_in_idx, -1.0)
    stamp_G!(ctx, I_in_idx, in_p,  1.0)
    stamp_G!(ctx, I_in_idx, in_n, -1.0)

    # Output current: gain * I_in flows into out_p (out of out_n)
    # Negative stamp means current entering the node
    stamp_G!(ctx, out_p, I_in_idx, -F.gain)
    stamp_G!(ctx, out_n, I_in_idx,  F.gain)

    return I_in_idx
end

#------------------------------------------------------------------------------#
# SPICE-style Current-Controlled Sources (reference existing V-source)
#------------------------------------------------------------------------------#

"""
    stamp!(H::CCVS, ctx::AnyMNAContext, out_p::Int, out_n::Int, I_in_idx::Int) -> Int

Stamp a CCVS using an existing current variable (SPICE-style).
V(out_p, out_n) = H.rm * I_in

I_in_idx is the index of an existing current variable (e.g., from a voltage source).
This is used when the SPICE netlist references a voltage source name for current sensing.

Returns I_out_idx - the index of the output current variable.
"""
function stamp!(H::CCVS, ctx::AnyMNAContext, out_p::Int, out_n::Int, I_in_idx::Int)
    # Output current variable (component-based API for zero allocation)
    I_out_idx = alloc_current!(ctx, :I_, H.name)

    # Output branch
    stamp_G!(ctx, out_p, I_out_idx,  1.0)
    stamp_G!(ctx, out_n, I_out_idx, -1.0)

    # Voltage equation: V(out) = rm * I(in)
    # V(out_p) - V(out_n) - rm * I_in = 0
    stamp_G!(ctx, I_out_idx, out_p,     1.0)
    stamp_G!(ctx, I_out_idx, out_n,    -1.0)
    stamp_G!(ctx, I_out_idx, I_in_idx, -H.rm)

    return I_out_idx
end

"""
    stamp!(F::CCCS, ctx::AnyMNAContext, out_p::Int, out_n::Int, I_in_idx::Int) -> Nothing

Stamp a CCCS using an existing current variable (SPICE-style).
I(out_p, out_n) = F.gain * I_in

I_in_idx is the index of an existing current variable (e.g., from a voltage source).
This is used when the SPICE netlist references a voltage source name for current sensing.
"""
function stamp!(F::CCCS, ctx::AnyMNAContext, out_p::Int, out_n::Int, I_in_idx::Int)
    # Output current: gain * I_in flows into out_p (out of out_n)
    # Negative stamp means current entering the node
    stamp_G!(ctx, out_p, I_in_idx, -F.gain)
    stamp_G!(ctx, out_n, I_in_idx,  F.gain)

    return nothing
end

# Overloads accepting CurrentIndex (returned by get_current_idx)
# These forward to the base implementation since stamp_G! handles CurrentIndex natively

"""
    stamp!(H::CCVS, ctx::AnyMNAContext, out_p::Int, out_n::Int, I_in_idx::CurrentIndex) -> CurrentIndex

Stamp a CCVS using an existing current variable (accepts CurrentIndex from get_current_idx).
"""
function stamp!(H::CCVS, ctx::AnyMNAContext, out_p::Int, out_n::Int, I_in_idx::CurrentIndex)
    # Output current variable (component-based API for zero allocation)
    I_out_idx = alloc_current!(ctx, :I_, H.name)

    # Output branch
    stamp_G!(ctx, out_p, I_out_idx,  1.0)
    stamp_G!(ctx, out_n, I_out_idx, -1.0)

    # Voltage equation: V(out) = rm * I(in)
    # V(out_p) - V(out_n) - rm * I_in = 0
    stamp_G!(ctx, I_out_idx, out_p,    1.0)
    stamp_G!(ctx, I_out_idx, out_n,   -1.0)
    stamp_G!(ctx, I_out_idx, I_in_idx, -H.rm)

    return I_out_idx
end

"""
    stamp!(F::CCCS, ctx::AnyMNAContext, out_p::Int, out_n::Int, I_in_idx::CurrentIndex) -> Nothing

Stamp a CCCS using an existing current variable (accepts CurrentIndex from get_current_idx).
"""
function stamp!(F::CCCS, ctx::AnyMNAContext, out_p::Int, out_n::Int, I_in_idx::CurrentIndex)
    # Output current: gain * I_in flows into out_p (out of out_n)
    # Negative stamp means current entering the node
    stamp_G!(ctx, out_p, I_in_idx, -F.gain)
    stamp_G!(ctx, out_n, I_in_idx,  F.gain)

    return nothing
end

#==============================================================================#
# Convenience: Stamp by node names
#==============================================================================#

"""
    stamp!(device, ctx::AnyMNAContext, p::Symbol, n::Symbol, ...)

Stamp a device using node names (automatically allocated).
"""
function stamp!(device, ctx::AnyMNAContext, p::Symbol, n::Symbol)
    stamp!(device, ctx, get_node!(ctx, p), get_node!(ctx, n))
end

function stamp!(device, ctx::AnyMNAContext, out_p::Symbol, out_n::Symbol, in_p::Symbol, in_n::Symbol)
    stamp!(device, ctx,
           get_node!(ctx, out_p), get_node!(ctx, out_n),
           get_node!(ctx, in_p), get_node!(ctx, in_n))
end

# Convenience for time-dependent sources with symbols (positional args)
# Works with unified VoltageSource{W} and CurrentSource{W} types
function stamp!(device::Union{VoltageSource, CurrentSource},
                ctx::AnyMNAContext, p::Symbol, n::Symbol, t::Real, mode::Symbol)
    stamp!(device, ctx, get_node!(ctx, p), get_node!(ctx, n), t, mode)
end

#==============================================================================#
# Behavioral Sources (B-sources)
#==============================================================================#

"""
    BehavioralVoltageSource{F}

A behavioral voltage source where V(p,n) is determined by evaluating an expression
that can reference other node voltages.

The `value_fn` is a function `(get_voltage) -> voltage` where `get_voltage(node)` returns
the voltage at a node by its symbol name.

# Example
```julia
# B-source: v=V(1)*2 makes V(p,n) = 2 * V(node_1)
bsrc = BehavioralVoltageSource(
    get_v -> 2.0 * get_v(Symbol("1")),
    name = :B5
)
```
"""
struct BehavioralVoltageSource{F} <: AbstractVoltageSource
    value_fn::F      # Function (get_voltage) -> value
    name::Symbol
end

function BehavioralVoltageSource(value_fn::F; name::Symbol=:B) where {F}
    BehavioralVoltageSource{F}(value_fn, name)
end

export BehavioralVoltageSource

"""
    BehavioralCurrentSource{F}

A behavioral current source where I(p,n) is determined by evaluating an expression
that can reference other node voltages.

The `value_fn` is a function `(get_voltage) -> current` where `get_voltage(node)` returns
the voltage at a node by its symbol name.

# Example
```julia
# B-source: i=V(1)*0.001 makes I(p,n) = V(node_1) / 1000
bsrc = BehavioralCurrentSource(
    get_v -> get_v(Symbol("1")) * 0.001,
    name = :B1
)
```
"""
struct BehavioralCurrentSource{F} <: AbstractCurrentSource
    value_fn::F      # Function (get_voltage) -> value
    name::Symbol
end

function BehavioralCurrentSource(value_fn::F; name::Symbol=:B) where {F}
    BehavioralCurrentSource{F}(value_fn, name)
end

export BehavioralCurrentSource

#------------------------------------------------------------------------------#
# Behavioral Voltage Source Stamping
#------------------------------------------------------------------------------#

"""
    stamp!(B::BehavioralVoltageSource, ctx::AnyMNAContext, p::Int, n::Int;
           get_voltage=nothing) -> Int

Stamp a behavioral voltage source. The source voltage is computed by calling
`B.value_fn(get_voltage)` where `get_voltage(node_name)` returns the voltage at that node.

For DC analysis, this requires an iterative Newton solver since the source value
depends on other node voltages.

In the linear approximation (first Newton iteration), we evaluate the expression
at the current solution estimate and stamp as a fixed voltage source.

Returns the index of the source current variable.
"""
function stamp!(B::BehavioralVoltageSource, ctx::AnyMNAContext, p::Int, n::Int;
                get_voltage=nothing)
    # Allocate current variable (component-based API for zero allocation)
    I_idx = alloc_current!(ctx, :I_, B.name)

    # KCL: current I flows from p through source to n
    stamp_G!(ctx, p, I_idx,  1.0)
    stamp_G!(ctx, n, I_idx, -1.0)

    # Voltage equation: Vp - Vn = V_behavioral
    stamp_G!(ctx, I_idx, p,  1.0)
    stamp_G!(ctx, I_idx, n, -1.0)

    # Compute the behavioral voltage value
    v = if get_voltage !== nothing
        B.value_fn(get_voltage)
    else
        # If no voltage accessor provided, use 0 (will be updated in Newton iteration)
        0.0
    end
    stamp_b!(ctx, I_idx, v)

    return I_idx
end

#------------------------------------------------------------------------------#
# Behavioral Current Source Stamping
#------------------------------------------------------------------------------#

"""
    stamp!(B::BehavioralCurrentSource, ctx::AnyMNAContext, p::Int, n::Int;
           get_voltage=nothing)

Stamp a behavioral current source. The source current is computed by calling
`B.value_fn(get_voltage)` where `get_voltage(node_name)` returns the voltage at that node.

Positive current flows from n to p (into the positive terminal p).
"""
function stamp!(B::BehavioralCurrentSource, ctx::AnyMNAContext, p::Int, n::Int;
                get_voltage=nothing)
    # Compute the behavioral current value
    i = if get_voltage !== nothing
        B.value_fn(get_voltage)
    else
        # If no voltage accessor provided, use 0 (will be updated in Newton iteration)
        0.0
    end

    # Current flows from n to p (into positive terminal)
    stamp_b!(ctx, p,  i)
    stamp_b!(ctx, n, -i)
    return nothing
end

# Convenience for behavioral sources with symbol nodes
function stamp!(B::Union{BehavioralVoltageSource, BehavioralCurrentSource},
                ctx::AnyMNAContext, p::Symbol, n::Symbol; get_voltage=nothing)
    stamp!(B, ctx, get_node!(ctx, p), get_node!(ctx, n); get_voltage=get_voltage)
end

#==============================================================================#
# Phase 6: Nonlinear Devices
#==============================================================================#

#==============================================================================#
# PCNR Newton Limiting (see doc/pcnr_plan.md)
#
# pnjlim is the SPICE PN-junction limiter, ported verbatim from the ngspice
# variant shipped in-repo as Verilog-A (DEVpnjlim in
# models/VADistillerModels.jl/va/diode.va). PNJunctionLimit packages the
# limiter parameters as a refine spec for alloc_limit!; the PCNR corrector
# (_dc_pcnr_newton in solve.jl) applies refine_limit between Newton steps.
#==============================================================================#

export pnjlim, PNJunctionLimit

"""
    pnjlim(vnew, vold, vt, vcrit) -> (vlim, limited::Bool)

SPICE PN-junction voltage limiter: propose an evaluation voltage between
`vold` (the voltage the device was evaluated at last iteration) and `vnew`
(the voltage Newton proposes), compressing large forward-bias jumps
logarithmically. Fixed point: `pnjlim(v, v, vt, vcrit) == v` for `v ≤ vcrit`.

Port of `DEVpnjlim` from `models/VADistillerModels.jl/va/diode.va` (the
ngspice variant, including its negative-voltage clamp).
"""
function pnjlim(vnew::Float64, vold::Float64, vt::Float64, vcrit::Float64)
    if vnew > vcrit && abs(vnew - vold) > vt + vt
        if vold > 0.0
            arg = (vnew - vold) / vt
            if arg > 0.0
                return vold + vt * (2.0 + log(arg - 2.0)), true
            else
                return vold - vt * (2.0 + log(2.0 - arg)), true
            end
        else
            return vt * log(vnew / vt), true
        end
    elseif vnew < 0.0
        # Negative vnew: ngspice reverse-bias clamp
        arg = vold > 0.0 ? -vold - 1.0 : 2.0 * vold - 1.0
        if vnew < arg
            return arg, true
        end
    end
    return vnew, false
end

"""
    PNJunctionLimit(vt, vcrit)

Refine spec for PN-junction limiting variables (pass as `refine=` to
`alloc_limit!`). `vt` is the (ideality-scaled) thermal voltage n·Vt and
`vcrit = n·Vt·ln(n·Vt / (√2·Is))` the critical voltage.
"""
struct PNJunctionLimit
    vt::Float64
    vcrit::Float64
end

function PNJunctionLimit(; Is::Real, Vt::Real, n::Real=1.0)
    nVt = Float64(n) * Float64(Vt)
    PNJunctionLimit(nVt, nVt * log(nVt / (sqrt(2.0) * Float64(Is))))
end

"""
    refine_limit(spec, vnew, vold) -> Float64

Apply a limiting variable's corrector: given the Newton-proposed value `vnew`
and the previous iterate's value `vold`, return the value the device should
evaluate at next. `nothing` specs pass `vnew` through.
"""
refine_limit(::Nothing, vnew::Float64, vold::Float64) = vnew
refine_limit(spec::PNJunctionLimit, vnew::Float64, vold::Float64) =
    pnjlim(vnew, vold, spec.vt, spec.vcrit)[1]

"""
    limit_initial_value(spec) -> Float64

Initial value for a limiting variable when the DC solve starts from scratch
(SPICE seeds junctions at vcrit so the exponential starts in a live region).
"""
limit_initial_value(::Nothing) = 0.0
limit_initial_value(spec::PNJunctionLimit) = spec.vcrit

"""
    Diode(; Is=1e-14, Vt=0.026, n=1.0, name=:D)

Ideal diode with exponential I-V characteristic: I = Is * (exp(V/(n*Vt)) - 1)

This is a nonlinear device that requires Newton iteration for DC analysis.
The stamp! method takes `x` parameter for the current operating point.

# Parameters
- `Is`: Saturation current (default: 1e-14 A)
- `Vt`: Thermal voltage (default: 0.026 V ≈ kT/q at 300K)
- `n`: Ideality factor (default: 1.0)
- `name`: Device name

# Example
```julia
function build_circuit(params, spec; x=ZERO_VECTOR)
    ctx = MNAContext()
    vin = get_node!(ctx, :vin)
    out = get_node!(ctx, :out)

    stamp!(VoltageSource(5.0), ctx, vin, 0)
    stamp!(Resistor(1000.0), ctx, vin, out)
    stamp!(Diode(Is=1e-14), ctx, out, 0; x=x)

    return ctx
end

sol = solve_dc(build_circuit, (;), MNASpec(mode=:dcop))
```
"""
struct Diode
    Is::Float64    # Saturation current
    Vt::Float64    # Thermal voltage
    n::Float64     # Ideality factor
    limit::Bool    # PCNR junction limiting (see doc/pcnr_plan.md)
    name::Symbol
end

function Diode(; Is::Real=1e-14, Vt::Real=0.026, n::Real=1.0, limit::Bool=true, name::Symbol=:D)
    Diode(Float64(Is), Float64(Vt), Float64(n), limit, name)
end

export Diode

# Diode I-V evaluation with linear extension above exponent 80 (like limexp):
# keeps I and G finite for wildly wrong intermediate iterates without moving
# any fixed point in the physical range.
@inline function _diode_iv(Is::Float64, nVt::Float64, v::Float64)
    xarg = v / nVt
    if xarg > 80.0
        e80 = exp(80.0)
        I0 = Is * (e80 * (1.0 + (xarg - 80.0)) - 1.0)
        Gd = Is / nVt * e80
    else
        expterm = exp(xarg)
        I0 = Is * (expterm - 1.0)
        Gd = Is / nVt * expterm
    end
    return I0, Gd
end

"""
    stamp!(D::Diode, ctx::AnyMNAContext, p::Int, n::Int; x::AbstractVector=Float64[])

Stamp a nonlinear diode into MNA matrices.

Uses Newton companion model: linearize I(V) at the evaluation point.

With `D.limit == true` (default), the diode uses a PCNR limiting variable
(doc/pcnr_plan.md): it evaluates at `v_lim = x[lim]` instead of `V_p - V_n`,
stamps its conductance into the `v_lim` *column*, and adds the linear row
`g_lim = v_lim - (V_p - V_n) = 0`. Under plain Newton this is step-for-step
equivalent to the unlimited diode (Schur complement identity); the PCNR
corrector applies `pnjlim` to `v_lim` between iterations for SPICE-style
convergence robustness.

With `D.limit == false`, stamps the classic companion model at `V0 = V_p - V_n`:
- G matrix: conductance G(V0) between p and n
- b vector: Newton companion current Ieq = I0 - G*V0

The x parameter provides the current solution vector.
"""
function stamp!(D::Diode, ctx::AnyMNAContext, p::Int, n::Int;
                x::AbstractVector=Float64[])
    # Get operating point voltage
    Vp = p == 0 ? 0.0 : (isempty(x) ? 0.0 : x[p])
    Vn = n == 0 ? 0.0 : (isempty(x) ? 0.0 : x[n])
    V0 = Vp - Vn

    Is, Vt, n_factor = D.Is, D.Vt, D.n
    nVt = n_factor * Vt

    if D.limit
        # PCNR: allocate the limiting variable (unconditional — keeps
        # DirectStampContext counters synchronized) and evaluate at it.
        lidx = alloc_limit!(ctx, :vdlim, D.name, p, n;
                            refine=PNJunctionLimit(Is=Is, Vt=Vt, n=n_factor))
        li = resolve_index(ctx, lidx)
        w = li <= length(x) ? x[li] : 0.0

        I0, Gd = _diode_iv(Is, nVt, w)

        # KCL rows: current depends on v_lim only — conductance goes in the
        # v_lim column (J_MNA/lim), nothing in the node-node block.
        stamp_G!(ctx, p, lidx,  Gd)
        stamp_G!(ctx, n, lidx, -Gd)

        # Companion current so the row residual equals I(w) at this iterate
        Ieq = I0 - Gd * w
        stamp_b!(ctx, p, -Ieq)
        stamp_b!(ctx, n,  Ieq)

        # Limiting row: g_lim = v_lim - (V_p - V_n) = 0 (linear, J_lim/lim = 1)
        stamp_G!(ctx, lidx, lidx, 1.0)
        stamp_G!(ctx, lidx, p, -1.0)
        stamp_G!(ctx, lidx, n,  1.0)
    else
        I0, Gd = _diode_iv(Is, nVt, V0)

        # Newton companion model: I = G*V + Ieq where Ieq = I0 - G*V0
        Ieq = I0 - Gd * V0

        # Stamp conductance (same pattern as resistor)
        stamp_conductance!(ctx, p, n, Gd)

        # Stamp companion current source
        # Current I flows from p to n (out of p, into n in MNA convention)
        # So: -Ieq enters p, +Ieq enters n
        stamp_b!(ctx, p, -Ieq)
        stamp_b!(ctx, n,  Ieq)
    end

    return nothing
end

"""
    DiodeWithCap(; Is=1e-14, Vt=0.026, n=1.0, Cj0=1e-12, Vj=0.7, m=0.5, name=:D)

Diode with nonlinear junction capacitance.

Combines the exponential I-V characteristic with voltage-dependent
depletion capacitance model: Cj(V) = Cj0 / (1 - V/Vj)^m

For forward bias (V > Vj), the capacitance is clamped to avoid singularity.

# Parameters
- `Is`: Saturation current (default: 1e-14 A)
- `Vt`: Thermal voltage (default: 0.026 V)
- `n`: Ideality factor (default: 1.0)
- `Cj0`: Zero-bias junction capacitance (default: 1e-12 F)
- `Vj`: Junction potential (default: 0.7 V)
- `m`: Grading coefficient (default: 0.5)
- `name`: Device name

# Charge Model
The junction charge is:
    q(V) = Cj0 * Vj * (1 - (1 - V/Vj)^(1-m)) / (1-m)  for V < Vj

For transient analysis, the capacitor current is I = dq/dt.
"""
struct DiodeWithCap
    Is::Float64    # Saturation current
    Vt::Float64    # Thermal voltage
    n::Float64     # Ideality factor
    Cj0::Float64   # Zero-bias junction capacitance
    Vj::Float64    # Junction potential
    m::Float64     # Grading coefficient
    name::Symbol
end

function DiodeWithCap(; Is::Real=1e-14, Vt::Real=0.026, n::Real=1.0,
                       Cj0::Real=1e-12, Vj::Real=0.7, m::Real=0.5, name::Symbol=:D)
    DiodeWithCap(Float64(Is), Float64(Vt), Float64(n),
                 Float64(Cj0), Float64(Vj), Float64(m), name)
end

export DiodeWithCap

"""
    diode_junction_cap(V, Cj0, Vj, m) -> Float64

Compute the junction capacitance at voltage V.

Cj(V) = Cj0 / (1 - V/Vj)^m

For V approaching Vj, we use a linear extrapolation to avoid singularity.
"""
function diode_junction_cap(V, Cj0, Vj, m)
    # Clamp to avoid singularity near V = Vj
    Vmax = 0.9 * Vj
    if V < Vmax
        return Cj0 / (1 - V/Vj)^m
    else
        # Linear extrapolation from Vmax
        C_at_max = Cj0 / (1 - Vmax/Vj)^m
        dC_dV = Cj0 * m / Vj / (1 - Vmax/Vj)^(m+1)
        return C_at_max + dC_dV * (V - Vmax)
    end
end

"""
    diode_junction_charge(V, Cj0, Vj, m) -> Float64

Compute the junction charge at voltage V.

q(V) = ∫ Cj(V) dV = Cj0 * Vj / (1-m) * (1 - (1 - V/Vj)^(1-m))

For V approaching Vj, we use continuation.
"""
function diode_junction_charge(V, Cj0, Vj, m)
    # Clamp to avoid singularity
    Vmax = 0.9 * Vj
    if V < Vmax
        if abs(m - 1.0) < 1e-10
            # Special case: m = 1 -> q = Cj0 * Vj * log(1 - V/Vj)
            return -Cj0 * Vj * log(1 - V/Vj)
        else
            return Cj0 * Vj / (1 - m) * (1 - (1 - V/Vj)^(1-m))
        end
    else
        # Continuation: q(V) = q(Vmax) + Cj(Vmax) * (V - Vmax)
        q_at_max = Cj0 * Vj / (1 - m) * (1 - (1 - Vmax/Vj)^(1-m))
        C_at_max = Cj0 / (1 - Vmax/Vj)^m
        return q_at_max + C_at_max * (V - Vmax)
    end
end

export diode_junction_cap, diode_junction_charge

"""
    stamp!(D::DiodeWithCap, ctx::AnyMNAContext, p::Int, n::Int; x::AbstractVector=Float64[])

Stamp a diode with junction capacitance.

This stamps both:
1. Resistive part: Nonlinear I-V (same as Diode)
2. Reactive part: Voltage-dependent capacitance Cj(V)

For transient analysis, the capacitor current is I = dq/dt = C(V) * dV/dt.
"""
function stamp!(D::DiodeWithCap, ctx::AnyMNAContext, p::Int, n::Int;
                x::AbstractVector=Float64[])
    # Get operating point voltage
    Vp = p == 0 ? 0.0 : (isempty(x) ? 0.0 : x[p])
    Vn = n == 0 ? 0.0 : (isempty(x) ? 0.0 : x[n])
    V0 = Vp - Vn

    # === Resistive Part (DC current) ===
    Is, Vt, n_factor = D.Is, D.Vt, D.n
    nVt = n_factor * Vt

    expterm = exp(V0 / nVt)
    I0 = Is * (expterm - 1.0)
    G = Is / nVt * expterm

    Ieq = I0 - G * V0

    # Stamp conductance
    stamp_conductance!(ctx, p, n, G)

    # Stamp companion current
    stamp_b!(ctx, p, -Ieq)
    stamp_b!(ctx, n,  Ieq)

    # === Reactive Part (Junction Capacitance) ===
    Cj0, Vj, m = D.Cj0, D.Vj, D.m

    # Capacitance at operating point
    C = diode_junction_cap(V0, Cj0, Vj, m)

    # Stamp capacitance
    stamp_capacitance!(ctx, p, n, C)

    return nothing
end

#==============================================================================#
# Phase 6: Simple MOSFET Model
#==============================================================================#

"""
    SimpleMOSFET(; Vth=0.5, K=1e-3, lambda=0.0, Cgd=1e-15, Cgs=1e-15, name=:M)

Simple long-channel MOSFET model for testing.

Uses square-law model in saturation:
    Ids = K/2 * (Vgs - Vth)^2 * (1 + lambda*Vds)  for Vgs > Vth, Vds > Vgs - Vth

Linear region:
    Ids = K * ((Vgs - Vth)*Vds - Vds^2/2)  for Vgs > Vth, Vds < Vgs - Vth

# Parameters
- `Vth`: Threshold voltage (default: 0.5 V)
- `K`: Transconductance parameter (default: 1e-3 A/V²)
- `lambda`: Channel length modulation (default: 0)
- `Cgd`: Gate-drain capacitance (default: 1e-15 F)
- `Cgs`: Gate-source capacitance (default: 1e-15 F)
- `name`: Device name

This is NOT a BSIM4-level model. It's a simple model for testing the
multi-port stamping infrastructure.
"""
struct SimpleMOSFET
    Vth::Float64     # Threshold voltage
    K::Float64       # Transconductance parameter
    lambda::Float64  # Channel length modulation
    Cgd::Float64     # Gate-drain capacitance
    Cgs::Float64     # Gate-source capacitance
    name::Symbol
end

function SimpleMOSFET(; Vth::Real=0.5, K::Real=1e-3, lambda::Real=0.0,
                       Cgd::Real=1e-15, Cgs::Real=1e-15, name::Symbol=:M)
    SimpleMOSFET(Float64(Vth), Float64(K), Float64(lambda),
                 Float64(Cgd), Float64(Cgs), name)
end

export SimpleMOSFET

"""
    stamp!(M::SimpleMOSFET, ctx::AnyMNAContext, d::Int, g::Int, s::Int;
           x::AbstractVector=Float64[])

Stamp a simple MOSFET (3-terminal: drain, gate, source).

Uses ForwardDiff to compute transconductances gm, gds from the square-law model.
"""
function stamp!(M::SimpleMOSFET, ctx::AnyMNAContext, d::Int, g::Int, s::Int;
                x::AbstractVector=Float64[])
    # Get operating point voltages
    Vd = d == 0 ? 0.0 : (isempty(x) ? 0.0 : x[d])
    Vg = g == 0 ? 0.0 : (isempty(x) ? 0.0 : x[g])
    Vs = s == 0 ? 0.0 : (isempty(x) ? 0.0 : x[s])

    Vgs = Vg - Vs
    Vds = Vd - Vs

    Vth, K, lambda = M.Vth, M.K, M.lambda

    # Compute drain current and derivatives
    if Vgs <= Vth
        # Cutoff
        Ids = 0.0
        gm = 0.0    # dIds/dVgs
        gds = 0.0   # dIds/dVds
    elseif Vds <= Vgs - Vth
        # Linear region
        Ids = K * ((Vgs - Vth) * Vds - Vds^2 / 2)
        gm = K * Vds
        gds = K * (Vgs - Vth - Vds)
    else
        # Saturation
        Ids = K / 2 * (Vgs - Vth)^2 * (1 + lambda * Vds)
        gm = K * (Vgs - Vth) * (1 + lambda * Vds)
        gds = K / 2 * (Vgs - Vth)^2 * lambda
    end

    # Newton companion: Ids = gm*(Vg-Vs) + gds*(Vd-Vs) + Ieq
    # where Ieq = Ids - gm*Vgs - gds*Vds
    Ieq = Ids - gm * Vgs - gds * Vds

    # Stamp drain current (flows from drain to source)
    # Current leaves drain (d), enters source (s)
    # dIds/dVd = gds, dIds/dVg = gm, dIds/dVs = -(gm + gds)

    # G matrix contributions
    stamp_G!(ctx, d, d,  gds)
    stamp_G!(ctx, d, g,  gm)
    stamp_G!(ctx, d, s, -(gds + gm))

    stamp_G!(ctx, s, d, -gds)
    stamp_G!(ctx, s, g, -gm)
    stamp_G!(ctx, s, s,  gds + gm)

    # Companion current
    stamp_b!(ctx, d, -Ieq)
    stamp_b!(ctx, s,  Ieq)

    # === Capacitances ===
    # Simple linear caps (not voltage-dependent for this simple model)
    # Cgs between g and s
    stamp_capacitance!(ctx, g, s, M.Cgs)
    # Cgd between g and d
    stamp_capacitance!(ctx, g, d, M.Cgd)

    return nothing
end

# 4-terminal version with body (bulk)
function stamp!(M::SimpleMOSFET, ctx::AnyMNAContext, d::Int, g::Int, s::Int, b::Int;
                x::AbstractVector=Float64[])
    # For the simple model, body is not connected (ignore body effect)
    # Just call 3-terminal version
    stamp!(M, ctx, d, g, s; x=x)
    return nothing
end
