name = "PSPModels"
uuid = "abf2981e-f194-4833-b9e6-388029af7f41"
authors = ["JuliaHub, Inc. and other contributors"]
version = "0.1.0"

[deps]
Cadnip = "28ce5535-9df1-4533-abc1-da0fb7327efb"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
NyanVerilogAParser = "28caa042-5edb-4d1f-abcd-02ce41b2dd3d"

[sources]
Cadnip = {path = "../.."}
NyanVerilogAParser = {path = "../../NyanVerilogAParser.jl"}
