name = "PhotonicModels"
uuid = "b332cf46-470c-43e0-97f7-46dbfe290ae1"
version = "0.1.0"

[deps]
Cadnip = "28ce5535-9df1-4533-abc1-da0fb7327efb"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
NyanVerilogAParser = "28caa042-5edb-4d1f-abcd-02ce41b2dd3d"

[sources]
Cadnip = {path = "../.."}
NyanVerilogAParser = {path = "../../NyanVerilogAParser.jl"}
